// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfJPkpib9L5wmwgmO7IPiRpfzt4FSB88Q',
    appId: '1:16309517426:web:bb9f6f16c2d26fb71bd6eb',
    messagingSenderId: '16309517426',
    projectId: 'daliy-75039',
    authDomain: 'daliy-75039.firebaseapp.com',
    databaseURL: 'https://daliy-75039.firebaseio.com',
    storageBucket: 'daliy-75039.firebasestorage.app',
    measurementId: 'G-4L448D2QHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOdtJDJCKrY0svWQ0-jxT7V7s4GHl0jsw',
    appId: '1:16309517426:android:5f86ddef61326e861bd6eb',
    messagingSenderId: '16309517426',
    projectId: 'daliy-75039',
    databaseURL: 'https://daliy-75039.firebaseio.com',
    storageBucket: 'daliy-75039.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzUp9ON1JKkpIzK4Azg4iTVk8y_tr8D1w',
    appId: '1:16309517426:ios:d396c069847b98121bd6eb',
    messagingSenderId: '16309517426',
    projectId: 'daliy-75039',
    databaseURL: 'https://daliy-75039.firebaseio.com',
    storageBucket: 'daliy-75039.firebasestorage.app',
    iosBundleId: 'com.example.garageManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzUp9ON1JKkpIzK4Azg4iTVk8y_tr8D1w',
    appId: '1:16309517426:ios:d396c069847b98121bd6eb',
    messagingSenderId: '16309517426',
    projectId: 'daliy-75039',
    databaseURL: 'https://daliy-75039.firebaseio.com',
    storageBucket: 'daliy-75039.firebasestorage.app',
    iosBundleId: 'com.example.garageManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfJPkpib9L5wmwgmO7IPiRpfzt4FSB88Q',
    appId: '1:16309517426:web:6bb3d931025bb3841bd6eb',
    messagingSenderId: '16309517426',
    projectId: 'daliy-75039',
    authDomain: 'daliy-75039.firebaseapp.com',
    databaseURL: 'https://daliy-75039.firebaseio.com',
    storageBucket: 'daliy-75039.firebasestorage.app',
    measurementId: 'G-XRPGEZWJTN',
  );
}
